# Generated by Django 5.0.2 on 2024-03-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image4_product_is_featured_productgallery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Is_available',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Is_offer_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_perc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_offer',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
