# Generated by Django 5.0.2 on 2024-03-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_image1_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
