# Generated by Django 5.0.2 on 2024-08-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
