# Generated by Django 5.0.2 on 2024-08-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_banner_banner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_description',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
