# Generated by Django 5.0.2 on 2024-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_banner_banner_description_banner_banner_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='banneractive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=50, null=True, unique=True)),
                ('banner_title', models.CharField(max_length=50, null=True, unique=True)),
                ('banner_description', models.CharField(max_length=50, null=True, unique=True)),
                ('banner_image', models.ImageField(blank=True, upload_to='photos/banner')),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
    ]
