# Generated by Django 5.1 on 2024-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannertwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=50, null=True, unique=True)),
                ('banner_title', models.CharField(max_length=50, null=True, unique=True)),
                ('banner_description', models.CharField(max_length=50, null=True, unique=True)),
                ('banner_image', models.ImageField(blank=True, upload_to='photos/banner')),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
    ]
