# Generated by Django 5.1 on 2024-08-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_bannertwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannertwo',
            name='banner_name',
        ),
    ]
