# Generated by Django 5.1 on 2024-10-06 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_remove_bannertwo_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_offer',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
