# Generated by Django 5.1 on 2024-10-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_alter_category_offer_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_Offer',
        ),
    ]
