# Generated by Django 5.0.2 on 2024-08-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_todo_category_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_offer',
            name='category',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='Category_Offer',
        ),
    ]
